name: Build Go app and push Ubuntu-based Docker image

# Trigger on push to main (adjust branches as needed)
on:
  push:
    branches:
      - main

# Required perms to push to GitHub Container Registry
permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/${{ github.repository }} # ghcr.io/<owner>/<owner/repo>
      SHORT_SHA: ${{ github.sha }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'   # adjust as needed

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build Go binary
        # Adjust output name/flags if required
        run: |
          go env -w GO111MODULE=on
          go mod tidy
          CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o ./bin/app ./...

      - name: Show built binary info
        run: ls -l ./bin || true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:sha-${{ github.run_number }}-${{ github.sha_short }}
            ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest
          file: ./Dockerfile
          build-args: |
            BINARY_PATH=./bin/app

      - name: Output image tags
        run: |
          echo "Image pushed:"
          echo " - ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:sha-${{ github.run_number }}-${{ github.sha_short }}"
          echo " - ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest
